"""add qualite tables

Revision ID: 213d3ab43700
Revises: 39c151049463
Create Date: 2025-11-21 11:34:07.376666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213d3ab43700'
down_revision = '39c151049463'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

