"""ajout_gestion_api

Revision ID: 32018db5f380
Revises: b0f00b92966a
Create Date: 2025-11-21 09:25:09.481341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32018db5f380'
down_revision = 'b0f00b92966a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

