"""ajout_gestion_qualite

Revision ID: 39c151049463
Revises: b1570e2eba11
Create Date: 2025-11-21 10:48:36.827882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c151049463'
down_revision = 'b1570e2eba11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

