"""enrich_essai_models_with_all_parameters

Revision ID: 7ea71076c19d
Revises: 001_initial
Create Date: 2025-11-17 10:43:00.795575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea71076c19d'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ajouter les nouvelles colonnes
    op.add_column('essais_atterberg', sa.Column('wl_nombre_coups_1', sa.Integer(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('wl_teneur_eau_1', sa.Float(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('wl_nombre_coups_2', sa.Integer(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('wl_teneur_eau_2', sa.Float(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('wl_nombre_coups_3', sa.Integer(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('wl_teneur_eau_3', sa.Float(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('wl_methode', sa.String(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('wp_teneur_eau_1', sa.Float(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('wp_teneur_eau_2', sa.Float(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('wp_teneur_eau_3', sa.Float(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('wr_teneur_eau', sa.Float(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('volume_initial', sa.Float(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('volume_final', sa.Float(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('masse_seche', sa.Float(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('humidite_relative', sa.Float(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('wr', sa.Float(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('ir', sa.Float(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('ia', sa.Float(), nullable=True))
    op.add_column('essais_atterberg', sa.Column('classification', sa.String(), nullable=True))
    op.create_index(op.f('ix_essais_atterberg_id'), 'essais_atterberg', ['id'], unique=False)
    
    # Migrer les données existantes avant de supprimer les anciennes colonnes
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE essais_atterberg 
        SET wl_nombre_coups_1 = wl_nombre_coups,
            wl_teneur_eau_1 = wl_teneur_eau,
            wp_teneur_eau_1 = wp_teneur_eau
        WHERE wl_nombre_coups IS NOT NULL OR wl_teneur_eau IS NOT NULL OR wp_teneur_eau IS NOT NULL
    """))
    
    # Supprimer les anciennes colonnes
    op.drop_column('essais_atterberg', 'wl_nombre_coups')
    op.drop_column('essais_atterberg', 'wp_teneur_eau')
    op.drop_column('essais_atterberg', 'wl_teneur_eau')
    op.add_column('essais_cbr', sa.Column('teneur_eau_preparation', sa.Float(), nullable=True))
    op.add_column('essais_cbr', sa.Column('densite_seche_preparation', sa.Float(), nullable=True))
    op.add_column('essais_cbr', sa.Column('energie_compactage', sa.String(), nullable=True))
    op.add_column('essais_cbr', sa.Column('nombre_couches', sa.Integer(), nullable=True))
    op.add_column('essais_cbr', sa.Column('nombre_coups', sa.Integer(), nullable=True))
    op.add_column('essais_cbr', sa.Column('points_penetration', sa.JSON(), nullable=True))
    op.add_column('essais_cbr', sa.Column('teneur_eau_finale', sa.Float(), nullable=True))
    op.add_column('essais_cbr', sa.Column('densite_seche_finale', sa.Float(), nullable=True))
    op.add_column('essais_cbr', sa.Column('gonflement', sa.Float(), nullable=True))
    op.add_column('essais_cbr', sa.Column('temps_immersion', sa.Integer(), nullable=True))
    op.add_column('essais_cbr', sa.Column('module_ev2', sa.Float(), nullable=True))
    op.add_column('essais_cbr', sa.Column('classe_portance', sa.String(), nullable=True))
    op.create_index(op.f('ix_essais_cbr_id'), 'essais_cbr', ['id'], unique=False)
    
    # Migrer les données existantes
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE essais_cbr 
        SET teneur_eau_finale = teneur_eau,
            densite_seche_finale = densite_seche
        WHERE teneur_eau IS NOT NULL OR densite_seche IS NOT NULL
    """))
    
    # Supprimer les anciennes colonnes
    op.drop_column('essais_cbr', 'teneur_eau')
    op.drop_column('essais_cbr', 'densite_seche')
    op.add_column('essais_granulometrie', sa.Column('type_essai', sa.String(), nullable=True))
    op.add_column('essais_granulometrie', sa.Column('methode', sa.String(), nullable=True))
    op.add_column('essais_granulometrie', sa.Column('masse_totale_seche', sa.Float(), nullable=True))
    op.add_column('essais_granulometrie', sa.Column('masse_apres_lavage', sa.Float(), nullable=True))
    op.add_column('essais_granulometrie', sa.Column('pourcentage_fines', sa.Float(), nullable=True))
    op.add_column('essais_granulometrie', sa.Column('points_sedimentometrie', sa.JSON(), nullable=True))
    op.add_column('essais_granulometrie', sa.Column('temperature_sedimentometrie', sa.Float(), nullable=True))
    op.add_column('essais_granulometrie', sa.Column('viscosite_dynamique', sa.Float(), nullable=True))
    op.add_column('essais_granulometrie', sa.Column('d16', sa.Float(), nullable=True))
    op.add_column('essais_granulometrie', sa.Column('d50', sa.Float(), nullable=True))
    op.add_column('essais_granulometrie', sa.Column('d84', sa.Float(), nullable=True))
    op.add_column('essais_granulometrie', sa.Column('cz', sa.Float(), nullable=True))
    op.add_column('essais_granulometrie', sa.Column('classe_granulometrique', sa.String(), nullable=True))
    op.add_column('essais_granulometrie', sa.Column('pourcentage_gravier', sa.Float(), nullable=True))
    op.add_column('essais_granulometrie', sa.Column('pourcentage_sable', sa.Float(), nullable=True))
    op.add_column('essais_granulometrie', sa.Column('pourcentage_limon', sa.Float(), nullable=True))
    op.add_column('essais_granulometrie', sa.Column('pourcentage_argile', sa.Float(), nullable=True))
    op.create_index(op.f('ix_essais_granulometrie_id'), 'essais_granulometrie', ['id'], unique=False)
    op.add_column('essais_proctor', sa.Column('diametre_moule', sa.Float(), nullable=True))
    op.add_column('essais_proctor', sa.Column('hauteur_moule', sa.Float(), nullable=True))
    op.add_column('essais_proctor', sa.Column('volume_moule', sa.Float(), nullable=True))
    op.add_column('essais_proctor', sa.Column('energie_compactage', sa.String(), nullable=True))
    op.add_column('essais_proctor', sa.Column('nombre_couches', sa.Integer(), nullable=True))
    op.add_column('essais_proctor', sa.Column('nombre_coups', sa.Integer(), nullable=True))
    op.add_column('essais_proctor', sa.Column('masse_mouton', sa.Float(), nullable=True))
    op.add_column('essais_proctor', sa.Column('hauteur_chute', sa.Float(), nullable=True))
    op.add_column('essais_proctor', sa.Column('masse_moule_vide', sa.Float(), nullable=True))
    op.add_column('essais_proctor', sa.Column('densite_humide_max', sa.Float(), nullable=True))
    op.add_column('essais_proctor', sa.Column('saturation_optimale', sa.Float(), nullable=True))
    op.add_column('essais_proctor', sa.Column('courbe_proctor', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_essais_proctor_id'), 'essais_proctor', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_essais_proctor_id'), table_name='essais_proctor')
    op.drop_column('essais_proctor', 'courbe_proctor')
    op.drop_column('essais_proctor', 'saturation_optimale')
    op.drop_column('essais_proctor', 'densite_humide_max')
    op.drop_column('essais_proctor', 'masse_moule_vide')
    op.drop_column('essais_proctor', 'hauteur_chute')
    op.drop_column('essais_proctor', 'masse_mouton')
    op.drop_column('essais_proctor', 'nombre_coups')
    op.drop_column('essais_proctor', 'nombre_couches')
    op.drop_column('essais_proctor', 'energie_compactage')
    op.drop_column('essais_proctor', 'volume_moule')
    op.drop_column('essais_proctor', 'hauteur_moule')
    op.drop_column('essais_proctor', 'diametre_moule')
    op.drop_index(op.f('ix_essais_granulometrie_id'), table_name='essais_granulometrie')
    op.drop_column('essais_granulometrie', 'pourcentage_argile')
    op.drop_column('essais_granulometrie', 'pourcentage_limon')
    op.drop_column('essais_granulometrie', 'pourcentage_sable')
    op.drop_column('essais_granulometrie', 'pourcentage_gravier')
    op.drop_column('essais_granulometrie', 'classe_granulometrique')
    op.drop_column('essais_granulometrie', 'cz')
    op.drop_column('essais_granulometrie', 'd84')
    op.drop_column('essais_granulometrie', 'd50')
    op.drop_column('essais_granulometrie', 'd16')
    op.drop_column('essais_granulometrie', 'viscosite_dynamique')
    op.drop_column('essais_granulometrie', 'temperature_sedimentometrie')
    op.drop_column('essais_granulometrie', 'points_sedimentometrie')
    op.drop_column('essais_granulometrie', 'pourcentage_fines')
    op.drop_column('essais_granulometrie', 'masse_apres_lavage')
    op.drop_column('essais_granulometrie', 'masse_totale_seche')
    op.drop_column('essais_granulometrie', 'methode')
    op.drop_column('essais_granulometrie', 'type_essai')
    op.add_column('essais_cbr', sa.Column('densite_seche', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('essais_cbr', sa.Column('teneur_eau', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_essais_cbr_id'), table_name='essais_cbr')
    op.drop_column('essais_cbr', 'classe_portance')
    op.drop_column('essais_cbr', 'module_ev2')
    op.drop_column('essais_cbr', 'temps_immersion')
    op.drop_column('essais_cbr', 'gonflement')
    op.drop_column('essais_cbr', 'densite_seche_finale')
    op.drop_column('essais_cbr', 'teneur_eau_finale')
    op.drop_column('essais_cbr', 'points_penetration')
    op.drop_column('essais_cbr', 'nombre_coups')
    op.drop_column('essais_cbr', 'nombre_couches')
    op.drop_column('essais_cbr', 'energie_compactage')
    op.drop_column('essais_cbr', 'densite_seche_preparation')
    op.drop_column('essais_cbr', 'teneur_eau_preparation')
    op.add_column('essais_atterberg', sa.Column('wl_teneur_eau', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('essais_atterberg', sa.Column('wp_teneur_eau', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('essais_atterberg', sa.Column('wl_nombre_coups', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_essais_atterberg_id'), table_name='essais_atterberg')
    op.drop_column('essais_atterberg', 'classification')
    op.drop_column('essais_atterberg', 'ia')
    op.drop_column('essais_atterberg', 'ir')
    op.drop_column('essais_atterberg', 'wr')
    op.drop_column('essais_atterberg', 'humidite_relative')
    op.drop_column('essais_atterberg', 'temperature')
    op.drop_column('essais_atterberg', 'masse_seche')
    op.drop_column('essais_atterberg', 'volume_final')
    op.drop_column('essais_atterberg', 'volume_initial')
    op.drop_column('essais_atterberg', 'wr_teneur_eau')
    op.drop_column('essais_atterberg', 'wp_teneur_eau_3')
    op.drop_column('essais_atterberg', 'wp_teneur_eau_2')
    op.drop_column('essais_atterberg', 'wp_teneur_eau_1')
    op.drop_column('essais_atterberg', 'wl_methode')
    op.drop_column('essais_atterberg', 'wl_teneur_eau_3')
    op.drop_column('essais_atterberg', 'wl_nombre_coups_3')
    op.drop_column('essais_atterberg', 'wl_teneur_eau_2')
    op.drop_column('essais_atterberg', 'wl_nombre_coups_2')
    op.drop_column('essais_atterberg', 'wl_teneur_eau_1')
    op.drop_column('essais_atterberg', 'wl_nombre_coups_1')
    # ### end Alembic commands ###

