"""ajout_modeles_qualite_workflow_notifications

Revision ID: b0f00b92966a
Revises: 004_add_projets
Create Date: 2025-11-21 09:15:45.743412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f00b92966a'
down_revision = '004_add_projets'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('essais', 'projet')
    op.drop_constraint('projets_code_projet_key', 'projets', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('projets_code_projet_key', 'projets', ['code_projet'])
    op.add_column('essais', sa.Column('projet', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

