"""ajout_gestion_echantillonage

Revision ID: b1570e2eba11
Revises: 32018db5f380
Create Date: 2025-11-21 09:50:49.377584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1570e2eba11'
down_revision = '32018db5f380'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

